version: '3.8'

services:
  db:
    image: postgres:15
    container_name: klitama-db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: klitama
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: klitama-app
    command: sh -c "sleep 5 && python manage.py migrate && gunicorn klitama.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata: